/* Generated by wayland-scanner 1.23.1 */

/*
 * Copyright © 2018 Ilia Bozhinov
 * Copyright © 2020 Isaac Freund
 * Copyright © 2022 wb9688
 * Copyright © 2024 Victoria Brekenfeld
 *
 * Permission to use, copy, modify, distribute, and sell this
 * software and its documentation for any purpose is hereby granted
 * without fee, provided that the above copyright notice appear in
 * all copies and that both that copyright notice and this permission
 * notice appear in supporting documentation, and that the name of
 * the copyright holders not be used in advertising or publicity
 * pertaining to distribution of the software without specific,
 * written prior permission.  The copyright holders make no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied
 * warranty.
 *
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
 * SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
 * THIS SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface ext_workspace_handle_v1_interface;
extern const struct wl_interface wl_output_interface;
extern const struct wl_interface wl_seat_interface;
extern const struct wl_interface wl_surface_interface;
extern const struct wl_interface zcosmic_toplevel_handle_v1_interface;
extern const struct wl_interface zcosmic_workspace_handle_v1_interface;

static const struct wl_interface *cosmic_toplevel_management_unstable_v1_types[] = {
	NULL,
	&zcosmic_toplevel_handle_v1_interface,
	&zcosmic_toplevel_handle_v1_interface,
	&wl_seat_interface,
	&zcosmic_toplevel_handle_v1_interface,
	&zcosmic_toplevel_handle_v1_interface,
	&zcosmic_toplevel_handle_v1_interface,
	&zcosmic_toplevel_handle_v1_interface,
	&zcosmic_toplevel_handle_v1_interface,
	&wl_output_interface,
	&zcosmic_toplevel_handle_v1_interface,
	&zcosmic_toplevel_handle_v1_interface,
	&wl_surface_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	&zcosmic_toplevel_handle_v1_interface,
	&zcosmic_workspace_handle_v1_interface,
	&wl_output_interface,
	&zcosmic_toplevel_handle_v1_interface,
	&zcosmic_toplevel_handle_v1_interface,
	&zcosmic_toplevel_handle_v1_interface,
	&ext_workspace_handle_v1_interface,
	&wl_output_interface,
};

static const struct wl_message zcosmic_toplevel_manager_v1_requests[] = {
	{ "destroy", "", cosmic_toplevel_management_unstable_v1_types + 0 },
	{ "close", "o", cosmic_toplevel_management_unstable_v1_types + 1 },
	{ "activate", "oo", cosmic_toplevel_management_unstable_v1_types + 2 },
	{ "set_maximized", "o", cosmic_toplevel_management_unstable_v1_types + 4 },
	{ "unset_maximized", "o", cosmic_toplevel_management_unstable_v1_types + 5 },
	{ "set_minimized", "o", cosmic_toplevel_management_unstable_v1_types + 6 },
	{ "unset_minimized", "o", cosmic_toplevel_management_unstable_v1_types + 7 },
	{ "set_fullscreen", "o?o", cosmic_toplevel_management_unstable_v1_types + 8 },
	{ "unset_fullscreen", "o", cosmic_toplevel_management_unstable_v1_types + 10 },
	{ "set_rectangle", "ooiiii", cosmic_toplevel_management_unstable_v1_types + 11 },
	{ "move_to_workspace", "2ooo", cosmic_toplevel_management_unstable_v1_types + 17 },
	{ "set_sticky", "3o", cosmic_toplevel_management_unstable_v1_types + 20 },
	{ "unset_sticky", "3o", cosmic_toplevel_management_unstable_v1_types + 21 },
	{ "move_to_ext_workspace", "4ooo", cosmic_toplevel_management_unstable_v1_types + 22 },
};

static const struct wl_message zcosmic_toplevel_manager_v1_events[] = {
	{ "capabilities", "a", cosmic_toplevel_management_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zcosmic_toplevel_manager_v1_interface = {
	"zcosmic_toplevel_manager_v1", 4,
	14, zcosmic_toplevel_manager_v1_requests,
	1, zcosmic_toplevel_manager_v1_events,
};

